### ISSUE TITLE
Question about contacts with multiple numbers on Android

### ISSUE THREAD

**Issue by aruhn1** [streem/react-native-select-contact#49]
As already stated in the description, when a contact has more than one number, on Android, the first number is automatically chosen. 

I want to know if there is a way on Android to allow to choose which of the different numbers should be used.

**Comment by seanadkinson** [comment]
According to the code [here](https://github.com/streem/react-native-select-contact/blob/master/index.js#L110), you may need to install the `react-native-action-sheet` module for Android, as mentioned in the `README`, in order to get the phone picker ui.  I'll close this issue assuming that is what's wrong, but feel free to reopen if needed.  Thanks
